### PR TITLE
PWX-10210 Update vendor tree to pull in api changes for Kubernetes 1.16

### PR DESCRIPTION
**Pull request by rodrigc**
**What this PR does / why we need it**:

Upgrades vendor tree, and also converts to use go modules for the vendor tree

**Which issue(s) this PR fixes** (optional)
Closes #PWX-10210

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rodrigc** [comment]
I modified the px-wipe script to use `docker.portworx.co/portworx/talisman:PWX-10210` and ran it against a Kubernetes 1.16 cluster with Portworx on it:

```
Script started on Tue 22 Oct 2019 07:35:41 PM UTC
]0;root@craighost2:~[?1034h[root@craighost2 ~]# ./x[Kpx-wipe
The operation will delete Portworx components and metadata from the cluster. The operation is irreversible and will lead to DATA LOSS. Do you want to continue? [y/N]:y
Parsed version is 1.16
Parsed client version (int) is 116
serviceaccount/talisman-account created
clusterrolebinding.rbac.authorization.k8s.io/talisman-role-binding created
job.batch/talisman created
Talisman job for wiping Portworx started. Monitor logs using: 'kubectl logs -n kube-system -l job-name=talisman'
Pod that will perform wipe of Portworx is still in container creating phase
waiting on talisman to complete...
Monitoring logs of pod: talisman-qq6sw
time="2019-10-22T19:35:50Z" level=info msg="Running talisman: 0c024dd-PWX-10210"
time="2019-10-22T19:35:50Z" level=info msg="Attempting to parse kvdb info from Portworx daemonset"
time="2019-10-22T19:35:50Z" level=info msg="Deleting all PX Kubernetes components from the cluster in namespaces: [kube-system]"
time="2019-10-22T19:35:52Z" level=info msg="Started daemonSet: [kube-system] px-node-wiper"
2019/10/22 19:35:52 app px-node-wiper is not ready yet. Cause: Observed generation is still 0. Check back status after some time Next retry in: 15s
2019/10/22 19:36:08 app px-node-wiper is not ready yet. Cause: 3 pods are not available. available: 0 ready: 0. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:false ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:false node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:false node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:36:23 app px-node-wiper is not ready yet. Cause: 3 pods are not available. available: 0 ready: 0. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:false ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:false node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:false node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:36:38 app px-node-wiper is not ready yet. Cause: 3 pods are not available. available: 0 ready: 0. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:false ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:false node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:false node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:36:54 app px-node-wiper is not ready yet. Cause: 2 pods are not available. available: 1 ready: 1. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:false ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:true node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:false node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:37:09 app px-node-wiper is not ready yet. Cause: 1 pods are not available. available: 2 ready: 2. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:false ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:true node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:true node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:37:24 app px-node-wiper is not ready yet. Cause: 1 pods are not available. available: 2 ready: 2. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:true ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:true node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:true node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:37:39 app px-node-wiper is not ready yet. Cause: 1 pods are not available. available: 2 ready: 2. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:true ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:true node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:true node:70.0.68.37
 Next retry in: 15s
2019/10/22 19:37:54 app px-node-wiper is not ready yet. Cause: 1 pods are not available. available: 2 ready: 2. Current pods overview:
  pod name:px-node-wiper-65l4x namespace:kube-system running:true ready:false node:70.0.68.31
  pod name:px-node-wiper-kxvdl namespace:kube-system running:true ready:true node:70.0.68.20
  pod name:px-node-wiper-vmpxx namespace:kube-system running:true ready:true node:70.0.68.37
 Next retry in: 15s
time="2019-10-22T19:38:09Z" level=info msg="Validated successful run of daemonset: [kube-system] px-node-wiper"
time="2019-10-22T19:38:09Z" level=info msg="Cluster is using internal etcd. No need to wipe kvdb."
Portworx cluster wipe succesfully completed.
job.batch "talisman" deleted
serviceaccount "talisman-account" deleted
clusterrolebinding.rbac.authorization.k8s.io "talisman-role-binding" deleted
customresourcedefinition.apiextensions.k8s.io "volumeplacementstrategies.portworx.io" deleted
]0;root@craighost2:~[root@craighost2 ~]# exit

Script done on Tue 22 Oct 2019 07:38:28 PM UTC
```

**Comment by harsh-px** [comment]
I verified this on 1.13 today and it looks fine. So just need to test this on 1.11 now

**Comment by rodrigc** [comment]
@harsh I ran the following experiment

**Step 1.  Set up a kubernetes 1.11.3 cluster, and install Portworx 2.1.5 on it**

```
kubectl --kubeconfig ./k8s/clusterGroup0/kubeconfig version --short
Client Version: v1.14.2
Server Version: v1.11.3
```

```
/opt/pwx/bin/pxctl --version
pxctl version 2.1.5.0-3b73452
```

```
/opt/pwx/bin/pxctl status
Status: PX is operational
License: Trial (expires in 31 days)
Node ID: f7d251f5-2c7e-4dcd-b698-c639b880eac7
        IP: 70.0.52.214
        Local Storage Pool: 2 pools
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE  USED    STATUS  ZONE    REGION
        0       HIGH            raid0           32 GiB  3.6 GiB Online  default default
        1       HIGH            raid0           384 GiB 12 GiB  Online  default default
        Local Storage Devices: 4 devices
        Device  Path            Media Type              Size            Last-Scan
        0:1     /dev/sdb        STORAGE_MEDIUM_MAGNETIC 32 GiB          02 Dec 19 21:28 UTC
        1:1     /dev/sdc        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 21:28 UTC
        1:2     /dev/sdd        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 21:28 UTC
        1:3     /dev/sde        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 21:28 UTC
        total                   -                       416 GiB
Cluster Summary
        Cluster ID: local-spddry-19-12-02-20-51-58-px-int
        Cluster UUID: ee25783f-d29d-457f-b2ff-098bbdf3b9d1
        Scheduler: kubernetes
        Nodes: 3 node(s) with storage (3 online)
        IP              ID                                      SchedulerNodeName               StorageNode     Used    Capacity        Status  StorageStatus   Version         Kernel
        70.0.52.214     f7d251f5-2c7e-4dcd-b698-c639b880eac7    craig-k8s-16-topaz-chopper-1    Yes             16 GiB  416 GiB         Online  Up (This node)  2.1.5.0-3b73452 3.10.0-862.3.2.el7.x86_64C
        70.0.52.226     585d2960-37f4-41f7-919e-13ecb6a63c87    craig-k8s-16-topaz-chopper-0    Yes             16 GiB  416 GiB         Online  Up              2.1.5.0-3b73452 3.10.0-862.3.2.el7.x86_64C
        70.0.52.228     3dc62213-5d33-42b8-bf40-38dc3e15923a    craig-k8s-16-topaz-chopper-2    Yes             16 GiB  416 GiB         Online  Up              2.1.5.0-3b73452 3.10.0-862.3.2.el7.x86_64C
Global Storage Pool
        Total Used      :  47 GiB
        Total Capacity  :  1.2 TiB
```


I then hacked the upgrade script to use talisman image `docker.portworx.co/portworx/talisman:PWX-10210`, and ran the upgrade.

Upgrade to Portworx 2.2.0 completed successfully.

```
Status: PX is operational
License: Trial (expires in 31 days)
Node ID: 585d2960-37f4-41f7-919e-13ecb6a63c87
        IP: 70.0.52.226
        Local Storage Pool: 2 pools
        POOL    IO_PRIORITY     RAID_LEVEL      USABLE  USED    STATUS  ZONE    REGION
        0       HIGH            raid0           32 GiB  3.6 GiB Online  default default
        1       HIGH            raid0           384 GiB 12 GiB  Online  default default
        Local Storage Devices: 4 devices
        Device  Path            Media Type              Size            Last-Scan
        0:1     /dev/sdb        STORAGE_MEDIUM_MAGNETIC 32 GiB          02 Dec 19 22:00 UTC
        1:1     /dev/sdc        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 22:00 UTC
        1:2     /dev/sdd        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 22:00 UTC
        1:3     /dev/sde        STORAGE_MEDIUM_MAGNETIC 128 GiB         02 Dec 19 22:00 UTC
        total                   -                       416 GiB
        Cache Devices:
        No cache devices
Cluster Summary
        Cluster ID: local-spddry-19-12-02-20-51-58-px-int
        Cluster UUID: ee25783f-d29d-457f-b2ff-098bbdf3b9d1
        Scheduler: kubernetes
        Nodes: 3 node(s) with storage (3 online)
        IP              ID                                      SchedulerNodeName               StorageNode     Used    Capacity        Status  StorageStatus   Version         Kernel
        70.0.52.214     f7d251f5-2c7e-4dcd-b698-c639b880eac7    craig-k8s-16-topaz-chopper-1    Yes             16 GiB  416 GiB         Online  Up              2.2.0.0-51db0fd 3.10.0-862.3.2.el7.x86_64
        70.0.52.226     585d2960-37f4-41f7-919e-13ecb6a63c87    craig-k8s-16-topaz-chopper-0    Yes             16 GiB  416 GiB         Online  Up (This node)  2.2.0.0-51db0fd 3.10.0-862.3.2.el7.x86_64
        70.0.52.228     3dc62213-5d33-42b8-bf40-38dc3e15923a    craig-k8s-16-topaz-chopper-2    Yes             16 GiB  416 GiB         Online  Up              2.2.0.0-51db0fd 3.10.0-862.3.2.el7.x86_64
Global Storage Pool
        Total Used      :  47 GiB
        Total Capacity  :  1.2 TiB
```

**Comment by rodrigc** [comment]
```
kubectl version --short
Client Version: v1.15.2
Server Version: v1.11.3
```

```
kubectl -n kube-system get ds.app portworx -o yaml

apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{"portworx.com/install-source":"https://install.portworx.com/?mc=false\u0026kbver=1.11.3\u0026b=true\u0026f=true\u0026j=auto\u0
    kubernetes.io/change-cause: update PX to portworx/oci-monitor:2.2.0
    portworx.com/install-source: https://install.portworx.com/?mc=false&kbver=1.11.3&b=true&f=true&j=auto&c=px-cluster-c8599a58-a5bf-4f13-96e1-e3478afe13c6&stork=true&lh=true&st=k8s
  creationTimestamp: "2019-12-02T20:51:59Z"
  generation: 3
  labels:
    name: portworx
  name: portworx
  namespace: kube-system
  resourceVersion: "12428"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/portworx
  uid: 95e370bd-1545-11ea-a4b6-000c2956f0ab
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: portworx
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: portworx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      containers:
      - args:
        - -c
        - px-cluster-c8599a58-a5bf-4f13-96e1-e3478afe13c6
        - -A
        - -f
        - -secret_type
        - k8s
        - -j
        - auto
        - -b
        - -x
        - kubernetes
        env:
        - name: AUTO_NODE_RECOVERY_TIMEOUT_IN_SECS
          value: "1500"
        - name: PX_TEMPLATE_VERSION
          value: v4
        image: portworx/oci-monitor:2.2.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /status
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 840
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: portworx
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /health
            port: 9015
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /tmp/px-termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/cores
          name: diagsdump
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /run/containerd
          name: containerdsock
        - mountPath: /var/run/crio
          name: criosock
        - mountPath: /etc/crictl.yaml
          name: crioconf
        - mountPath: /etc/pwx
          name: etcpwx
        - mountPath: /opt/pwx
          name: optpwx
        - mountPath: /host_proc
          name: procmount
        - mountPath: /etc/systemd/system
          name: sysdmount
        - mountPath: /var/run/log
          name: journalmount1
          readOnly: true
        - mountPath: /var/log
          name: journalmount2
          readOnly: true
        - mountPath: /var/run/dbus
          name: dbusmount
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: px-account
      serviceAccountName: px-account
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/cores
          type: ""
        name: diagsdump
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersock
      - hostPath:
          path: /run/containerd
          type: ""
        name: containerdsock
      - hostPath:
          path: /var/run/crio
          type: ""
        name: criosock
      - hostPath:
          path: /etc/crictl.yaml
          type: FileOrCreate
        name: crioconf
      - hostPath:
          path: /etc/pwx
          type: ""
        name: etcpwx
      - hostPath:
          path: /opt/pwx
          type: ""
        name: optpwx
      - hostPath:
          path: /proc
          type: ""
        name: procmount
      - hostPath:
          path: /etc/systemd/system
          type: ""
        name: sysdmount
      - hostPath:
          path: /var/run/log
          type: ""
        name: journalmount1
      - hostPath:
          path: /var/log
          type: ""
        name: journalmount2
      - hostPath:
          path: /var/run/dbus
          type: ""
        name: dbusmount
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 3
  updatedNumberScheduled: 3
```

**Comment by harsh-px** [comment]
Nice. This is good to merge in that case.

@mborodin-px please keep on eye on the upgrade jobs over next few days after this merges in case there is any regression.

**Comment by rodrigc** [comment]
I also hacked px-wipe to use `docker.portworx.co/portworx/talisman:PWX-10210`
and after running it:

```
Portworx cluster wipe succesfully completed.
```

**Comment by rodrigc** [comment]
@harsh-px I cannot write to this repo, so you will have to merge

**Pull request merged**
